
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pejqibapmpglcmfeqzbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlanFpYmFwbXBnbGNtZmVxemJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwODg1MTMsImV4cCI6MjA2MjY2NDUxM30.iZs4uSC3885CDP-ipHZO8OGPwtXCZZuhIbaz3_vQ214";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
